casscroute_blog_homepage:
    path:     /
    defaults: { _controller: CasscrouteBlogBundle:Blog:index }

casscroute_blog_post:
    path:     /post/{id}
    defaults: { _controller: CasscrouteBlogBundle:Blog:post }

casscroute_crud_new:
    path:     /new
    defaults: { _controller: CasscrouteBlogBundle:Crud:new }

casscroute_crud_edit:
    path:     /edit/{id}
    defaults: { _controller: CasscrouteBlogBundle:Crud:edit }
    requirements:
        id: \d+
