casscroute_blog_homepage:
    path:     /
    defaults: { _controller: CasscrouteBlogBundle:Blog:index }

casscroute_blog_post:
    path:     /post/{alias}
    defaults: { _controller: CasscrouteBlogBundle:Blog:post }

casscroute_blog_listpost:
    path:     /page/{page}
    defaults: { _controller: CasscrouteBlogBundle:Blog:index }

casscroute_crud_new:
    path:     /new
    defaults: { _controller: CasscrouteBlogBundle:Crud:new }

casscroute_crud_edit:
    path:     /edit/{alias}
    defaults: { _controller: CasscrouteBlogBundle:Crud:edit }

casscroute_crud_delete:
    path:       /delete/{alias}
    defaults:   { _controller: CasscrouteBlogBundle:Crud:delete }
