<?php

namespace Casscroute\BlogBundle\Entity;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPosts($page, $numberPerPage)
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.published', 'DESC')
            ->getQuery();
        $query
            ->setFirstResult(($page-1) * $numberPerPage)
            ->setMaxResults($numberPerPage)
        ;
        return new Paginator($query, true);
    }
}
